import Link from "next/link";
import { UserPlus } from "lucide-react";
import { requireAdminPermission } from "@/lib/admin-auth";
import { getDb } from "@/lib/db";

export default async function StudentsPage({ searchParams }: { searchParams: Promise<{ q?: string; batch?: string; status?: string; lifecycle?: string }> }) {
  await requireAdminPermission("students:manage"); const filters = await searchParams;
  const students = await getDb().student.findMany({ where: { AND: [filters.lifecycle === "all" ? {} : { isActive: filters.lifecycle !== "archived" }, filters.q ? { OR: [{ fullName: { contains: filters.q, mode: "insensitive" } }, { studentCode: { contains: filters.q, mode: "insensitive" } }, { email: { contains: filters.q, mode: "insensitive" } }, { phone: { contains: filters.q } }, { collegeName: { contains: filters.q, mode: "insensitive" } }] } : {}, filters.batch ? { enrollments: { some: { batchId: filters.batch } } } : {}, filters.status ? { enrollments: { some: { status: filters.status as "PENDING" | "CONFIRMED" | "ENROLLED" | "ACTIVE" | "COMPLETED" | "DROPPED" | "CANCELLED" } } } : {}] }, orderBy: { createdAt: "desc" }, take: 250, include: { account: true, enrollments: { orderBy: { enrolledAt: "desc" }, take: 1, include: { batch: { include: { course: true } } } } } });
  const batches = await getDb().batch.findMany({ orderBy: { startDate: "desc" }, select: { id: true, code: true, name: true } });
  return <div className="admin-page"><div className="admin-page-head"><div><p className="admin-kicker">Student lifecycle</p><h1>Students</h1><p>Search, update, archive and restore student records.</p></div><Link className="admin-primary" href="/admin/students/new"><UserPlus />Add student</Link></div><form className="admin-filters" action="/admin/students"><input name="q" defaultValue={filters.q} placeholder="Name, code, email, phone, college"/><select name="batch" defaultValue={filters.batch}><option value="">All batches</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{batch.code} · {batch.name}</option>)}</select><select name="status" defaultValue={filters.status}><option value="">All enrollment statuses</option>{["PENDING", "CONFIRMED", "ENROLLED", "ACTIVE", "COMPLETED", "DROPPED", "CANCELLED"].map((status) => <option key={status}>{status}</option>)}</select><select name="lifecycle" defaultValue={filters.lifecycle || "active"}><option value="active">Active students</option><option value="archived">Archived students</option><option value="all">All students</option></select><button className="admin-primary">Filter</button></form><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Student</th><th>Contact</th><th>College</th><th>Current enrollment</th><th>Record</th><th>Portal</th></tr></thead><tbody>{students.map((student) => { const enrollment = student.enrollments[0]; return <tr key={student.id}><td><Link className="admin-row-link" href={`/admin/students/${student.id}`}>{student.fullName}</Link><small>{student.studentCode}</small></td><td>{student.email}<small>{student.phone}</small></td><td>{student.collegeName}</td><td>{enrollment?.batch.course.name || "—"}<small>{enrollment ? `${enrollment.batch.code} · ${enrollment.status}` : "No enrollment"}</small></td><td>{student.isActive ? "Active" : "Archived"}</td><td>{student.account?.isActive && student.isActive ? "Enabled" : "Disabled"}</td></tr>; })}</tbody></table>{!students.length && <p className="admin-empty">No students match these filters.</p>}</div></div>;
}
