import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2, GraduationCap, UserRoundCheck } from "lucide-react";
import { CTASection } from "@/components/CTASection";
import { PageHero } from "@/components/PageHero";
import { ProgramTimeline } from "@/components/ProgramTimeline";
import { SectionHeading } from "@/components/SectionHeading";
import { programJourney } from "@/data/program";

export const metadata: Metadata = { title: "60-Day Program", description: "Explore SaiTech Labs' intensive 60-day technology and career-readiness program." };
const audience = ["B.Tech 3rd Year", "B.Tech Final Year", "Recent Graduates"];
export default function ProgramPage() { return <><PageHero eyebrow="Intensive 60-Day Program" title="A focused journey from fundamentals to career readiness." description="Build technical understanding, apply what you learn, communicate with confidence and prepare for real-world interviews."><Link href="/admissions" className="button button-gold">Enroll now <ArrowRight /></Link></PageHero><section className="section"><div className="container split-section"><div><SectionHeading align="left" eyebrow="Who should join?" title="Built for ambitious technology learners" description="The program is structured for learners who want practical exposure alongside a strong technical foundation." /><div className="audience-cards">{audience.map((item, i) => <div key={item}><span>0{i + 1}</span><GraduationCap /><strong>{item}</strong></div>)}</div></div><aside className="info-panel"><UserRoundCheck /><h3>A structured learning environment</h3><p>This program is designed for serious learners who want guided practice, clear progression and career-relevant preparation.</p><ul><li><CheckCircle2 />Concept-led instruction</li><li><CheckCircle2 />Guided practical sessions</li><li><CheckCircle2 />Professional skill development</li></ul></aside></div></section><section className="section program-section"><div className="container"><SectionHeading light eyebrow="Program journey" title="Eight Steps. One Connected Experience." description="Each step builds on the previous one, keeping the learning journey clear and focused." /><ProgramTimeline /></div></section><section className="section soft-bg"><div className="container"><SectionHeading eyebrow="Learning approach" title="Learn. Practice. Build. Present. Interview." description="Progress comes from using knowledge—not only hearing it." /><div className="journey-row">{programJourney.map((item, i) => <div key={item}><span>0{i + 1}</span><strong>{item}</strong></div>)}</div></div></section><CTASection title="Give your learning a clear direction." text="Explore the 60-day program and speak with our team about the right starting point for you." /></>; }
