import Link from "next/link";
import { Download, Search } from "lucide-react";
import { admissionOrder, admissionWhere, PAGE_SIZE, pageNumber, queryLink } from "@/lib/admin-query";
import { getDb } from "@/lib/db";

type Params = Promise<Record<string, string | string[] | undefined>>;
const label = (value: string) => value.replaceAll("_", " ");
const formatDate = (value: Date) => new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(value);

export default async function Admissions({ searchParams }: { searchParams: Params }) {
  const params = await searchParams; const page = pageNumber(params.page); const where = admissionWhere(params); const db = getDb();
  const [rows, total, options] = await Promise.all([
    db.admission.findMany({ where, orderBy: admissionOrder(params.sort), skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE, include: { mockInterviews: { orderBy: { createdAt: "desc" }, take: 1 } } }),
    db.admission.count({ where }),
    Promise.all([db.admission.findMany({ distinct: ["course"], select: { course: true }, orderBy: { course: "asc" } }), db.admission.findMany({ distinct: ["qualification"], select: { qualification: true }, orderBy: { qualification: "asc" } })]),
  ]);
  const pages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const exportQuery = new URLSearchParams(Object.entries(params).flatMap(([key, value]) => typeof value === "string" ? [[key, value]] : []));
  return <div className="admin-page"><div className="admin-page-head"><div><p className="admin-kicker">Lead pipeline</p><h1>Admissions</h1><p>{total} matching submission{total === 1 ? "" : "s"}</p></div><a className="admin-secondary" href={`/api/admin/export/admissions?${exportQuery}`}><Download />Export filtered CSV</a></div>
    <form className="admin-filters"><label className="admin-search"><Search /><input name="q" defaultValue={String(params.q ?? "")} placeholder="Name, phone, email or college" /></label><select name="status" defaultValue={String(params.status ?? "")}><option value="">All statuses</option>{["NEW", "CONTACTED", "FOLLOW_UP", "JOINED", "NOT_INTERESTED"].map(value => <option key={value}>{value}</option>)}</select><select name="course" defaultValue={String(params.course ?? "")}><option value="">All courses</option>{options[0].map(value => <option key={value.course}>{value.course}</option>)}</select><select name="qualification" defaultValue={String(params.qualification ?? "")}><option value="">All qualifications</option>{options[1].map(value => <option key={value.qualification}>{value.qualification}</option>)}</select><select name="trainingMode" defaultValue={String(params.trainingMode ?? "")}><option value="">All modes</option><option>CLASSROOM</option><option>ONLINE</option><option>EITHER</option></select><select name="sort" defaultValue={String(params.sort ?? "")}><option value="">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name A-Z</option><option value="followup">Next follow-up</option></select><input name="from" type="date" defaultValue={String(params.from ?? "")} aria-label="From date" /><input name="to" type="date" defaultValue={String(params.to ?? "")} aria-label="To date" /><button className="admin-primary">Apply</button><Link className="admin-clear" href="/admin/admissions">Clear</Link></form>
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Student</th><th>Course</th><th>Contact</th><th>Status</th><th>Mock AI Interview</th><th>Submitted</th><th></th></tr></thead><tbody>{rows.map(row => { const interview = row.mockInterviews[0]; return <tr key={row.id}><td><strong>{row.studentName}</strong><small>{row.collegeName}</small></td><td>{row.course}<small>{label(row.trainingMode)}</small></td><td><a href={`tel:${row.phone}`}>{row.phone}</a><small>{row.email}</small></td><td><span className={`admin-status status-${row.leadStatus.toLowerCase()}`}>{label(row.leadStatus)}</span>{row.nextFollowUpAt && <small>Follow up {formatDate(row.nextFollowUpAt)}</small>}</td><td>{interview ? <Link href={`/admin/interviews/${interview.id}`}><strong>{interview.overallScore !== null ? `${interview.overallScore}%` : label(interview.status)}</strong><small>{interview.result !== "NOT_EVALUATED" ? label(interview.result) : interview.technologies.join(" + ")}</small></Link> : <small>Not created</small>}</td><td>{formatDate(row.createdAt)}</td><td><Link className="admin-row-link" href={`/admin/admissions/${row.id}`}>Open</Link></td></tr>; })}</tbody></table>{!rows.length && <p className="admin-empty">No admissions match these filters.</p>}</div><Pagination path="/admin/admissions" page={page} pages={pages} params={params} /></div>;
}

function Pagination({ path, page, pages, params }: { path: string; page: number; pages: number; params: Record<string, string | string[] | undefined> }) { return <nav className="admin-pagination" aria-label="Pagination"><Link aria-disabled={page <= 1} href={page > 1 ? queryLink(path, params, { page: page - 1 }) : "#"}>Previous</Link><span>Page {page} of {pages}</span><Link aria-disabled={page >= pages} href={page < pages ? queryLink(path, params, { page: page + 1 }) : "#"}>Next</Link></nav>; }
