import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, BrainCircuit, BriefcaseBusiness, Cloud, CodeXml, Database, GitBranch, GraduationCap, MessageSquareText, Mic2, PhoneCall, Rocket, Sparkles, Target, UserRoundCheck } from "lucide-react";
import { CTASection } from "@/components/CTASection";
import { CourseCard } from "@/components/CourseCard";
import { ProgramTimeline } from "@/components/ProgramTimeline";
import { SectionHeading } from "@/components/SectionHeading";
import { TrainerCard } from "@/components/TrainerCard";
import { courses } from "@/data/courses";
import { trainers } from "@/data/trainers";

export const metadata: Metadata = { alternates: { canonical: "https://www.saitechlabs.in/" } };

const values = [{ value: "60", suffix: "Days", label: "Intensive Program" }, { value: "Industry", suffix: "Experts", label: "Experienced Trainers" }, { value: "Hands-On", suffix: "Learning", label: "Practical Approach" }, { value: "Career", suffix: "Ready", label: "Interview Preparation" }];
const features = [
  [BriefcaseBusiness, "Industry Experts as Trainers"], [CodeXml, "Real-Time Projects & Case Studies"], [Rocket, "Hands-On Practical Learning"], [Target, "Interview Preparation"],
  [UserRoundCheck, "Resume Building Guidance"], [Mic2, "Soft Skills & Corporate Training"], [GraduationCap, "Career Readiness Focus"], [BadgeCheck, "Experienced IT Professionals"],
];

export default function Home() {
  return <>
    <section className="home-hero"><div className="hero-grid-lines" /><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /><div className="container hero-layout"><div className="hero-content"><div className="program-badge"><Sparkles /> Intensive 60-Day Program</div><p className="hero-kicker">Innovate <span>•</span> Educate <span>•</span> Accelerate</p><h1>Your launchpad to<br /><em>a top-tier IT career</em></h1><p className="hero-lead">Learn from industry professionals, build practical technology skills, and prepare yourself for real-world IT careers.</p><p className="audience-line"><GraduationCap />Designed for B.Tech 3rd Year, Final Year & Recent Graduates</p><div className="hero-actions"><Link className="button button-primary" href="/program">Explore program <ArrowRight /></Link><Link className="button button-outline" href="/admissions">Enroll now</Link></div><a className="counselor-link" href="tel:+919493969696"><span><PhoneCall /></span><span><small>Talk to a Counselor</small><strong>+91 94939 69696</strong></span></a></div><div className="hero-visual" aria-label="Technology learning pathways"><div className="tech-core"><span>STL</span><strong>Career<br />Launchpad</strong></div><div className="orbit orbit-a"><span><Cloud />Cloud</span><span><BrainCircuit />AI & ML</span></div><div className="orbit orbit-b"><span><GitBranch />DevOps</span><span><Database />Data</span></div><div className="code-panel"><span>LEARN</span><span>PRACTICE</span><span>BUILD</span></div></div></div></section>
    <section className="value-strip"><div className="container value-grid">{values.map(item => <div key={item.label}><strong>{item.value}</strong><span>{item.suffix}</span><small>{item.label}</small></div>)}</div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Practical by design" title="Build Skills That Industry Actually Needs" description="Technology fundamentals, practical training, real-world scenarios, communication, resume preparation and interview readiness — combined into one structured learning experience." /><div className="course-grid">{courses.map(course => <CourseCard course={course} key={course.slug} />)}</div></div></section>
    <section className="section program-section"><div className="container"><SectionHeading eyebrow="Intensive 60-Day Program" title="From Fundamentals to Career Readiness" description="A focused learning journey that moves from strong foundations to practical application and confident interview preparation." light /><ProgramTimeline /><div className="center-action"><Link className="button button-gold" href="/program">Explore the full journey <ArrowRight /></Link></div></div></section>
    <section className="section soft-bg"><div className="container"><SectionHeading eyebrow="The SaiTech difference" title="Why Choose SaiTech Labs?" description="A deliberate learning environment built for capability, confidence and professional growth." /><div className="feature-grid">{features.map(([Icon, title]) => { const FeatureIcon = Icon; return <article className="feature-card" key={String(title)}><FeatureIcon /><h3>{String(title)}</h3><p>Structured guidance that connects concepts with practical, career-relevant application.</p></article>; })}</div></div></section>
    <section className="philosophy"><div className="container philosophy-grid"><div><p className="eyebrow">Our training philosophy</p><h2>We Don&apos;t Just Teach Technology.<br /><span>We Build Competence.</span></h2><p>SaiTech Labs does not promise or guarantee jobs. Our objective is to build the technical knowledge, practical exposure, communication skills and confidence students need to perform strongly in interviews and begin their technology careers.</p></div><div className="competence-list">{[["01", "Knowledge"], ["02", "Practice"], ["03", "Confidence"], ["04", "Career Readiness"]].map(([n, title]) => <div key={n}><span>{n}</span><strong>{title}</strong></div>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Meet the mentors" title="Meet Our Industry Experts" description="Learn from professionals with real-world technology experience." /><div className="trainer-grid home-trainers">{trainers.slice(0, 3).map(t => <TrainerCard key={t.name} trainer={t} />)}</div><div className="center-action"><Link className="button button-outline" href="/trainers">Meet all trainers <ArrowRight /></Link></div></div></section>
    <section className="section promotions-section"><div className="container promotions-panel"><div><p className="eyebrow">Admissions & Announcements</p><h2>Latest from SaiTech Labs</h2><p>Program announcements and upcoming admission updates will appear here as official promotional material becomes available.</p><Link href="/admissions" className="text-button">View admissions <ArrowRight /></Link></div><div className="promo-placeholders"><div><MessageSquareText /><span>New announcements<br />coming soon</span></div><div><Sparkles /><span>Promotion asset<br />ready</span></div></div></div></section>
    <CTASection />
  </>;
}
