import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ShieldAlert } from "lucide-react";
import { InterviewManager } from "@/components/admin/InterviewForms";
import { requireAdminPermission } from "@/lib/admin-auth";
import { getDb } from "@/lib/db";
import { interviewTechnologies, rubricSchema } from "@/lib/interviews/config";

const formatDate = (value: Date) => new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(value);
export default async function InterviewAdminPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdminPermission("admissions:manage");
  const { id } = await params;
  const interview = await getDb().mockInterview.findUnique({ where: { id }, include: { admission: true, createdBy: { select: { name: true } }, questions: { orderBy: { position: "asc" }, include: { answer: { include: { evaluation: true } } } }, integrityEvents: { orderBy: { occurredAt: "asc" } } } });
  if (!interview) notFound();
  const manager = { id: interview.id, status: interview.status, questionCount: interview.questionCount, aiQuestionCount: interview.aiQuestionCount, manualQuestionCount: interview.manualQuestionCount, expiresAt: interview.expiresAt.toISOString(), started: Boolean(interview.startedAt), questions: interview.questions.map((question) => ({ id: question.id, position: question.position, source: question.source, technology: question.technology, difficulty: question.difficulty, questionText: question.questionText, referenceAnswer: question.referenceAnswer, rubric: rubricSchema.parse(question.rubric), maxScore: question.maxScore, approved: Boolean(question.approvedAt) })) };
  const evaluations = interview.questions.map((question) => question.answer?.evaluation).filter((value): value is NonNullable<typeof value> => Boolean(value));
  const average = (field: "technicalAccuracy" | "completeness" | "practicalKnowledge" | "clarity") => evaluations.length ? Math.round(evaluations.reduce((sum, value) => sum + value[field], 0) / evaluations.length) : 0;
  return <div className="admin-page"><Link className="admin-back" href={`/admin/admissions/${interview.admissionId}`}><ArrowLeft />Back to candidate</Link><div className="admin-page-head detail"><div><p className="admin-kicker">Mock interview · {interview.id}</p><h1>{interview.admission.studentName}</h1><p>{interview.technologies.join(" + ")} · {interview.experienceRange} · {interview.questionCount} questions · created by {interview.createdBy.name}</p></div>{interview.overallScore !== null && <div className="interview-score-badge"><strong>{interview.overallScore}%</strong><span>{interview.result.replaceAll("_", " ")}</span></div>}</div><InterviewManager interview={manager} technologies={interviewTechnologies} />
  {interview.status === "COMPLETED" && <section className="interview-report"><div className="admin-metrics"><Metric label="Technical accuracy" value={`${average("technicalAccuracy")}%`} /><Metric label="Completeness" value={`${average("completeness")}%`} /><Metric label="Practical knowledge" value={`${average("practicalKnowledge")}%`} /><Metric label="Clarity" value={`${average("clarity")}%`} /></div><section className="admin-panel integrity-report"><header><h2><ShieldAlert />Integrity timeline</h2><strong>{interview.integrityEvents.length} events</strong></header>{interview.integrityEvents.map((event) => <p key={event.id}><span>{event.type.replaceAll("_", " ")}</span><time>{formatDate(event.occurredAt)}</time></p>)}{!interview.integrityEvents.length && <p className="admin-empty">No integrity events recorded.</p>}</section><div className="interview-report-questions">{interview.questions.map((question) => <article className="admin-panel" key={question.id}><header><div><span>Question {question.position}</span><h2>{question.questionText}</h2></div><strong>{question.answer?.evaluation?.score ?? 0} / {question.maxScore}</strong></header><h3>Candidate answer</h3><p className="report-answer">{question.answer?.answerText || "No answer submitted."}</p><div className="report-feedback"><div><h3>Strengths</h3><ul>{question.answer?.evaluation?.strengths.map(value=><li key={value}>{value}</li>)}</ul></div><div><h3>Missing points</h3><ul>{question.answer?.evaluation?.missingPoints.map(value=><li key={value}>{value}</li>)}</ul></div></div><h3>AI feedback</h3><p>{question.answer?.evaluation?.feedback}</p><details><summary>Admin reference answer and rubric</summary><p>{question.referenceAnswer}</p><ul>{rubricSchema.parse(question.rubric).requiredPoints.map(value=><li key={value}>{value}</li>)}</ul></details></article>)}</div></section>}
  {interview.evaluationError && <p className="admin-alert error">Evaluation pending: {interview.evaluationError}</p>}</div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <article className="admin-metric"><div><small>{label}</small><strong>{value}</strong></div></article>; }
