import { notFound } from "next/navigation";
import { AttendanceForm, BatchEditForm, TrainerAssignmentForm } from "@/components/admin/OperationsForms";
import { requireAdminPermission } from "@/lib/admin-auth";
import { getDb } from "@/lib/db";
import { trainerCanAccessBatch } from "@/lib/trainer-scope";

export default async function BatchDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const admin = await requireAdminPermission("batches:manage"); const { id } = await params;
  if (!await trainerCanAccessBatch(admin, id)) notFound();
  const [batch, trainers] = await Promise.all([getDb().batch.findUnique({ where: { id }, include: { course: true, trainerAssignments: { include: { trainer: true } }, enrollments: { where: { status: { not: "CANCELLED" }, student: { isActive: true } }, include: { student: true } }, attendanceSessions: { orderBy: { sessionDate: "desc" }, include: { trainer: true, _count: { select: { records: true } } } } } }), getDb().trainer.findMany({ where: { isActive: true }, orderBy: { name: "asc" } })]);
  if (!batch) notFound();
  const studentOptions = batch.enrollments.map((enrollment) => ({ id: enrollment.student.id, label: `${enrollment.student.fullName} (${enrollment.student.studentCode})` }));
  const trainerOptions = trainers.map((trainer) => ({ id: trainer.id, label: trainer.name }));
  return <div className="admin-page"><div className="admin-page-head"><div><p className="admin-kicker">{batch.course.name}</p><h1>{batch.name}</h1><p>{batch.code} · {batch.mode} · {batch.status}</p></div></div><div className="admin-settings-grid"><section className="admin-panel"><h2>Batch details</h2><dl className="admin-definition"><div><dt>Dates</dt><dd>{batch.startDate.toLocaleDateString("en-IN")} – {batch.endDate.toLocaleDateString("en-IN")}</dd></div><div><dt>Capacity</dt><dd>{batch.enrollments.length} / {batch.capacity}</dd></div><div><dt>Trainers</dt><dd>{batch.trainerAssignments.map((assignment) => `${assignment.trainer.name} (${assignment.role.replaceAll("_", " ")})`).join(", ") || "Not assigned"}</dd></div></dl>{admin.role !== "TRAINER" && <><h3>Edit / delete batch</h3><BatchEditForm batch={{ id: batch.id, name: batch.name, startDate: batch.startDate.toISOString().slice(0,10), endDate: batch.endDate.toISOString().slice(0,10), mode: batch.mode, capacity: batch.capacity, status: batch.status }} /><h3>Assign trainer</h3><TrainerAssignmentForm batchId={batch.id} trainers={trainerOptions} /></>}</section><section className="admin-panel"><h2>Attendance history</h2>{batch.attendanceSessions.length ? <div className="admin-recent-list">{batch.attendanceSessions.map((session) => <article key={session.id}><strong>{session.topic}</strong><small>{session.sessionDate.toLocaleDateString("en-IN")} · {session.trainer?.name || "Trainer not specified"} · {session._count.records} records</small></article>)}</div> : <p className="admin-empty">No attendance sessions yet.</p>}</section></div><section className="admin-panel"><header><h2>Record attendance</h2><small>{studentOptions.length} active students</small></header><AttendanceForm batchId={batch.id} students={studentOptions} trainers={trainerOptions} /></section></div>;
}
