import Link from "next/link";
import { ArrowRight, CalendarCheck, ClipboardList, CreditCard, GraduationCap, MessageSquare, Users } from "lucide-react";
import { requireAdminPermission } from "@/lib/admin-auth";
import { can } from "@/lib/admin-permissions";
import { getDb } from "@/lib/db";
import { formatInr, paymentSummary } from "@/lib/operations";
import { batchScope } from "@/lib/trainer-scope";

export default async function Dashboard() {
  const admin = await requireAdminPermission("dashboard:view"); const db = getDb();
  if (admin.role === "TRAINER") {
    const batches = await db.batch.findMany({ where: { ...batchScope(admin), status: { in: ["OPEN", "ACTIVE"] } }, include: { course: true, enrollments: true, attendanceSessions: true } });
    return <DashboardFrame title="Trainer dashboard" description="Your assigned batches and attendance workload."><div className="admin-metrics"><Metric label="Assigned batches" value={String(batches.length)} icon={<Users/>}/><Metric label="Active students" value={String(batches.reduce((sum,batch)=>sum+batch.enrollments.length,0))} icon={<GraduationCap/>}/><Metric label="Sessions recorded" value={String(batches.reduce((sum,batch)=>sum+batch.attendanceSessions.length,0))} icon={<CalendarCheck/>}/><Metric label="Feedback queue" value={String(await db.feedback.count({where:{batchId:{in:batches.map(batch=>batch.id)},moderationStatus:"NEW"}}))} icon={<MessageSquare/>}/></div><section className="admin-panel"><h2>Assigned batches</h2>{batches.map(batch=><Link className="admin-row-link" key={batch.id} href={`/admin/batches/${batch.id}`}>{batch.code} · {batch.course.name}</Link>)}</section></DashboardFrame>;
  }
  const [admissions,students,batches,feedback,enrollments,payments] = await Promise.all([db.admission.count(),db.student.count(),db.batch.count({where:{status:"ACTIVE"}}),db.feedback.count({where:{moderationStatus:"NEW"}}),db.enrollment.findMany({where:{status:{notIn:["CANCELLED","DROPPED"]}},include:{payments:true}}),db.payment.findMany({where:{status:"RECEIVED"}})]);
  const received=payments.reduce((sum,item)=>sum+Number(item.amount),0); const outstanding=enrollments.reduce((sum,item)=>sum+Number(paymentSummary(item.finalFee,item.payments).balance),0);
  return <DashboardFrame title="Operations dashboard" description="Admissions, delivery, and finance at a glance."><div className="admin-metrics">{can(admin.role,"admissions:manage")&&<Metric label="Admissions" value={String(admissions)} icon={<ClipboardList/>}/>}<Metric label="Students" value={String(students)} icon={<GraduationCap/>}/>{can(admin.role,"batches:manage")&&<Metric label="Active batches" value={String(batches)} icon={<Users/>}/>} {can(admin.role,"payments:manage")&&<Metric label="Received" value={formatInr(received)} icon={<CreditCard/>}/>} {can(admin.role,"reports:view")&&<Metric label="Outstanding" value={formatInr(outstanding)} icon={<CreditCard/>}/>} {can(admin.role,"feedback:manage")&&<Metric label="New feedback" value={String(feedback)} icon={<MessageSquare/>}/>}</div><div className="admin-dashboard-grid">{can(admin.role,"admissions:manage")&&<Quick title="Admissions pipeline" detail="Review and convert prospective students." href="/admin/admissions"/>}{can(admin.role,"payments:manage")&&<Quick title="Payment operations" detail="Record collections, refunds, and balances." href="/admin/payments"/>}{can(admin.role,"attendance:manage")&&<Quick title="Attendance" detail="Record and review batch attendance." href="/admin/attendance"/>}{can(admin.role,"feedback:manage")&&<Quick title="Feedback queue" detail="Review consent and moderate responses." href="/admin/feedback"/>}</div></DashboardFrame>;
}
function DashboardFrame({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <div className="admin-page"><div className="admin-page-head"><div><p className="admin-kicker">Live overview</p><h1>{title}</h1><p>{description}</p></div></div>{children}</div>}
function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="admin-metric"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function Quick({title,detail,href}:{title:string;detail:string;href:string}){return <section className="admin-panel"><header><h2>{title}</h2><Link href={href}>Open <ArrowRight/></Link></header><p>{detail}</p></section>}
