"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Eye, EyeOff } from "lucide-react";

async function send(url: string, method: string, body?: unknown) { const response = await fetch(url, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const data = await response.json().catch(() => ({ message: "Something went wrong." })); if (!response.ok) throw new Error(data.message); return data; }
export function LoginForm() { const router = useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [show,setShow]=useState(false); async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const form=new FormData(e.currentTarget);try{await send("/api/admin/login","POST",{email:form.get("email"),password:form.get("password")});router.replace("/admin/dashboard");router.refresh();}catch(err){setError(err instanceof Error?err.message:"Unable to sign in.");setBusy(false);}} return <form className="admin-login-form" onSubmit={submit}><label>Email address<input name="email" type="email" autoComplete="username" required /></label><label>Password<div className="password-field"><input name="password" type={show?"text":"password"} autoComplete="current-password" required /><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="admin-alert error" role="alert">{error}</p>}<button className="admin-primary" disabled={busy}>{busy?"Signing in…":"Sign in securely"}</button></form> }

export function LeadUpdateForm({id,status,followUp}:{id:string;status:string;followUp:string}){const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);try{await send(`/api/admin/admissions/${id}/status`,"PATCH",{leadStatus:f.get("leadStatus"),nextFollowUpAt:f.get("nextFollowUpAt")||null});setMsg("Lead updated.");router.refresh();}catch(err){setMsg(err instanceof Error?err.message:"Update failed.");}finally{setBusy(false)}}return <form className="admin-action-form" onSubmit={submit}><label>Status<select name="leadStatus" defaultValue={status}>{["NEW","CONTACTED","FOLLOW_UP","JOINED","NOT_INTERESTED"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label><label>Next follow-up<input name="nextFollowUpAt" type="datetime-local" defaultValue={followUp}/></label><button className="admin-primary" disabled={busy}>{busy?"Saving…":"Save update"}</button>{msg&&<small role="status">{msg}</small>}</form>}

export function NoteForm({id}:{id:string}){const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget;const f=new FormData(form);try{await send(`/api/admin/admissions/${id}/notes`,"POST",{note:f.get("note")});form.reset();setMsg("Note added.");router.refresh();}catch(err){setMsg(err instanceof Error?err.message:"Could not add note.");}finally{setBusy(false)}}return <form className="admin-note-form" onSubmit={submit}><label>Add internal note<textarea name="note" minLength={2} maxLength={2000} required placeholder="Record the conversation or next action…" /></label><button className="admin-primary" disabled={busy}>{busy?"Adding…":"Add note"}</button>{msg&&<small role="status">{msg}</small>}</form>}

export function ContactStatusForm({id,status}:{id:string;status:string}){const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);await send(`/api/admin/contact-enquiries/${id}/status`,"PATCH",{status:f.get("status")});setMsg("Status updated.");router.refresh();}catch(err){setMsg(err instanceof Error?err.message:"Update failed.")}finally{setBusy(false)}}return <form className="admin-action-form inline" onSubmit={submit}><select name="status" defaultValue={status} aria-label="Enquiry status">{["NEW","CONTACTED","CLOSED"].map(v=><option key={v}>{v}</option>)}</select><button className="admin-primary" disabled={busy}>{busy?"Saving…":"Save"}</button>{msg&&<small>{msg}</small>}</form>}

export function PasswordForm(){const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);try{await send("/api/admin/settings/password","PATCH",{currentPassword:f.get("currentPassword"),newPassword:f.get("newPassword"),confirmPassword:f.get("confirmPassword")});setMsg("Password changed. Please sign in again.");setTimeout(()=>{router.replace("/admin/login");router.refresh()},900);}catch(err){setMsg(err instanceof Error?err.message:"Could not change password.");setBusy(false)}}return <form className="admin-settings-form" onSubmit={submit}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required /></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={12} required /><small>At least 12 characters with upper/lowercase, a number and symbol.</small></label><label>Confirm new password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} required /></label><button className="admin-primary" disabled={busy}>{busy?"Updating…":"Change password"}</button>{msg&&<p className="admin-alert" role="status">{msg}</p>}</form>}
