"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

async function request(url:string,method:"POST"|"PATCH",body?:unknown){const response=await fetch(url,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.message||"Request failed.");return result}

export function FeedbackModeration({id,current,canApprove}:{id:string;current:string;canApprove:boolean}){const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function update(status:string){setBusy(true);setMsg("");try{await request(`/api/admin/feedback/${id}`,"PATCH",{moderationStatus:status});router.refresh()}catch(error){setMsg(error instanceof Error?error.message:"Update failed.")}finally{setBusy(false)}}return <div className="queue-action"><select defaultValue={current} disabled={busy} onChange={(event)=>void update(event.target.value)}><option>NEW</option><option>REVIEWED</option>{canApprove&&<option>APPROVED</option>}<option>REJECTED</option></select>{msg&&<small>{msg}</small>}</div>}
export function PaymentStatusAction({id,current}:{id:string;current:string}){const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function update(status:string){setBusy(true);try{await request(`/api/admin/payments/${id}`,"PATCH",{status});router.refresh()}catch(error){setMsg(error instanceof Error?error.message:"Update failed.")}finally{setBusy(false)}}return <div className="queue-action"><select defaultValue={current} disabled={busy} onChange={(event)=>void update(event.target.value)}><option>RECEIVED</option><option>PENDING</option><option>FAILED</option><option>REFUNDED</option></select>{msg&&<small>{msg}</small>}</div>}
export function RevokeButton({url,label="Revoke"}:{url:string;label?:string}){const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function revoke(){if(!window.confirm(`${label} this record?`))return;setBusy(true);try{await request(url,"POST");router.refresh()}catch(error){setMsg(error instanceof Error?error.message:"Update failed.")}finally{setBusy(false)}}return <div className="queue-action"><button className="admin-secondary" onClick={revoke} disabled={busy}>{busy?"Updating...":label}</button>{msg&&<small>{msg}</small>}</div>}
