import { notFound } from "next/navigation";
import { CertificateIssueButton, PaymentForm, PublicLinkForm, StudentAccountForm, StudentInterviewAction } from "@/components/admin/OperationsForms";
import { requireAdminPermission } from "@/lib/admin-auth";
import { can } from "@/lib/admin-permissions";
import { getDb } from "@/lib/db";
import { formatInr, paymentSummary } from "@/lib/operations";

export default async function StudentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const admin = await requireAdminPermission("students:manage"); const { id } = await params;
  const student = await getDb().student.findUnique({ where: { id }, include: { account: true, enrollments: { orderBy: { enrolledAt: "desc" }, include: { batch: { include: { course: true } }, payments: { orderBy: { paymentDate: "desc" } }, certificates: true } }, attendance: { include: { session: true } }, feedback: { orderBy: { createdAt: "desc" }, take: 5 }, publicLinks: { orderBy: { createdAt: "desc" } }, notes: { orderBy: { createdAt: "desc" }, include: { createdBy: true } } } });
  if (!student) notFound();
  const attended = student.attendance.filter((record) => record.status === "PRESENT" || record.status === "LATE").length; const attendance = student.attendance.length ? Math.round(attended / student.attendance.length * 100) : 0;
  return <div className="admin-page"><div className="admin-page-head detail"><div><p className="admin-kicker">{student.studentCode}</p><h1>{student.fullName}</h1><p>{student.email} · {student.phone}</p></div></div><div className="admin-settings-grid"><section className="admin-panel"><h2>Profile</h2><dl className="admin-definition"><div><dt>College</dt><dd>{student.collegeName}</dd></div><div><dt>Qualification</dt><dd>{student.qualification} · {student.graduationYear}</dd></div><div><dt>State</dt><dd>{student.state}</dd></div><div><dt>Current status</dt><dd>{student.currentStatus}</dd></div><div><dt>Attendance</dt><dd>{attendance}% ({attended}/{student.attendance.length})</dd></div><div><dt>Portal</dt><dd>{student.account?.isActive ? "Enabled" : "Disabled"}</dd></div></dl></section><section className="admin-panel"><h2>Student portal access</h2><StudentAccountForm studentId={student.id} email={student.account?.email || student.email} />{can(admin.role, "admissions:manage") && <><h3>AI mock interview</h3><StudentInterviewAction studentId={student.id} /></>}</section></div>{student.enrollments.map((enrollment) => { const summary = paymentSummary(enrollment.finalFee, enrollment.payments); return <section className="admin-panel" key={enrollment.id}><header><div><h2>{enrollment.batch.course.name}</h2><small>{enrollment.batch.code} · {enrollment.status}</small></div></header><div className="admin-metrics"><Metric label="Final fee" value={formatInr(enrollment.finalFee)} /><Metric label="Paid" value={formatInr(summary.paid)} /><Metric label="Balance" value={formatInr(summary.balance)} /><Metric label="Payment status" value={summary.status.replaceAll("_", " ")} /></div><div className="admin-settings-grid">{can(admin.role, "payments:manage") && <div><h3>Record payment</h3><PaymentForm enrollmentId={enrollment.id} /></div>}{can(admin.role, "certificates:manage") && <div><h3>Certificate</h3>{enrollment.certificates.length ? <p>{enrollment.certificates[0].certificateNumber} · {enrollment.certificates[0].status}</p> : <CertificateIssueButton enrollmentId={enrollment.id} />}</div>}</div></section>; })}<div className="admin-settings-grid"><section className="admin-panel"><h2>Create public link</h2><PublicLinkForm studentId={student.id} enrollments={student.enrollments.map((enrollment) => ({ id: enrollment.id, label: `${enrollment.batch.course.name} · ${enrollment.batch.code}` }))} /></section><section className="admin-panel"><h2>Public link history</h2>{student.publicLinks.length ? <div className="admin-recent-list">{student.publicLinks.map((link) => <article key={link.id}><strong>{link.type.replaceAll("_", " ")}</strong><small>{link.isActive && !link.revokedAt ? "Active" : "Revoked"} · created {link.createdAt.toLocaleDateString("en-IN")}{link.expiresAt ? ` · expires ${link.expiresAt.toLocaleDateString("en-IN")}` : ""}</small></article>)}</div> : <p className="admin-empty">No links created.</p>}</section></div></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="admin-metric"><div><small>{label}</small><strong className="student-metric-value">{value}</strong></div></div>}
